# Generated by Django 4.2.3 on 2023-07-24 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinyapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShortenedURL',
            new_name='ShortenedURLStore',
        ),
    ]
